### PR TITLE
Update harbour-laufhelden-zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**
fix a lot of strings

### CODE REVIEW

**Comment by jdrescher2006** [comment]
This has conflicts, please fix them first!

**Comment by dashinfantry** [comment]
I don't understand.Can you explain? 星期四, 16 四月 2020, 06:56下午 +08:00 发件人 Jens Drescher  notifications@github.com :

**Comment by dashinfantry** [comment]
Can you explain?I don't understand.

**Comment by jdrescher2006** [comment]
No problem. I already fixed it.

**Pull request merged**
