### PR TITLE
Added Spanish(Spain) language

### PR DESCRIPTION
**Pull request by carmenfdezb**

### CODE REVIEW

**Comment by jdrescher2006** [comment]
Cool! Thanks for your work!

**Comment by jdrescher2006** [comment]
I am a little bit confused now. I noticed that we already had spanish language by cabballero: harbour-laufhelden-es.ts. Is your file an other language?

**Comment by carmenfdezb** [comment]
Hi @jdrescher2006!

Sorry for the confusion. es_ES file is the translation for Spaniards, and es file is Spanish in general. I only wanted to contribute in your project, some translations texts in es_ES file are different than es file

Sorry for the inconvenience, and if you feel that add es_ES to your project is not appropriate, don't do it.

Thanks for your excellent application.

**Comment by jdrescher2006** [comment]
@carmenfdezb good to hear that you like the app.
I didn't think about the widespread use of the spanish language and it's variants.
I will keep it!
Next release may take a little bit because I still have troubles with the cyclic voice announcements.

**Pull request merged**
