### PR TITLE
Initial send to strava support

### PR DESCRIPTION
**Pull request by piggz**
Added support for uploading activities to strava
Uses an oauth library, which contains a lot of functionality that isnt used, but may be useful for the future?  Options are to leave the full library as-is, or remove bits not required for this app.

The strava support is basic upload only, with options for name, description, type, privacy, commute.

### CODE REVIEW

**Comment by piggz** [comment]
Additionally, the app uses my strava application ID, which appears as https://www.strava.com/oauth/authorize?client_id=13707&response_type=code&redirect_uri=http://localhost&approval_prompt=force

**Comment by jdrescher2006** [comment]
Hi, thanks for your work!
I have a few questions:
- is it legal? I mean strava is a closed platform right?
- does it make sense to have your strava application ID and credentials in the code?
- I made a commit yesterday, could you solve the conflicting files?
- you forgot a lot of ; at the end of code lines
- do we need all the code? I think it would make more sense to only have the code which is really needed.

**Comment by piggz** [comment]
1. afaict it is perfectly legal, im only using the public api described at developer.strava.com
2. i can remove the id etc, but you will have to remember to add them back when building a binary.  alternatively, you could also register an application.
3. yes
4. damn javascript and its implicit line endings. yes i'll fix
5. i can remove the unnecessary sub classes, such as the facebook and twitter specific implementations. alternatively , i could add o2 as a git submodule?

**Comment by jdrescher2006** [comment]
1. very cool, i wasn't aware of this!
2. if it's OK for you, you can keep it as it is. I only thought someone might steel your credentials because everyone can see it on github
5. I think it's OK if you remove the demos/examples

**Comment by piggz** [comment]
looking further at the oauth2 spec, and strava docs, i might not even need the client secret, ill test this out later.

**Comment by piggz** [comment]
I think thats everything fixed up.

**Comment by piggz** [comment]
btw, the secret is required during token exchange, just not in initial auth.

**Comment by jdrescher2006** [comment]
That looks good! However there are still conflicts. Can you try to fix them?

**Pull request merged**
