### PR TITLE
Update harbour-laufhelden-zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**
enhance Chinese translation

### CODE REVIEW

**Comment by martonmiklos** [comment]
LGTM.

**Comment by martonmiklos** [comment]
@dashinfantry would you like to have a release with this update only, or you managed to install and test your translation?

**Comment by dashinfantry** [comment]
If you send me a test version,I will test it first.


 
---Original---

**Comment by dashinfantry** [comment]
An updating release is also good. It's Sailfish OS3.4 now.


 
---Original---

**Pull request merged**
